namespace Robmikh.Interop.Composition
{
	namespace Effects
	{
		enum EffectBorderMode
		{
			Soft = 0,
			Hard = 1,
		};

		enum EffectOptimization
		{
			Speed = 0,
			Balanced = 1,
			Quality = 2,
		};

		enum BlendEffectMode
		{
			Multiply = 0,
			Screen = 1,
			Darken = 2,
			Lighten = 3,
			Dissolve = 4,
			ColorBurn = 5,
			LinearBurn = 6,
			DarkerColor = 7,
			LighterColor = 8,
			ColorDodge = 9,
			LinearDodge = 10,
			Overlay = 11,
			SoftLight = 12,
			HardLight = 13,
			VividLight = 14,
			LinearLight = 15,
			PinLight = 16,
			HardMix = 17,
			Difference = 18,
			Exclusion = 19,
			Hue = 20,
			Saturation = 21,
			Color = 22,
			Luminosity = 23,
			Subtract = 24,
			Division = 25,
		};

		runtimeclass ColorSourceEffect : Windows.Graphics.Effects.IGraphicsEffect, Windows.Graphics.Effects.IGraphicsEffectSource
		{
			ColorSourceEffect();

			Windows.UI.Color Color{ get; set; };
			Windows.Foundation.Numerics.Vector4 ColorHdr{ get; set; };
		}

		runtimeclass GaussianBlurEffect : Windows.Graphics.Effects.IGraphicsEffect, Windows.Graphics.Effects.IGraphicsEffectSource
		{
			GaussianBlurEffect();

			Single BlurAmount { get; set; };
			EffectOptimization Optimization { get; set; };
			EffectBorderMode BorderMode { get; set; };
			Windows.Graphics.Effects.IGraphicsEffectSource Source { get; set; };
		}

		runtimeclass SaturationEffect : Windows.Graphics.Effects.IGraphicsEffect, Windows.Graphics.Effects.IGraphicsEffectSource
		{
			SaturationEffect();

			Single Saturation { get; set; };
			Windows.Graphics.Effects.IGraphicsEffectSource Source { get; set; };
		}

		runtimeclass BlendEffect : Windows.Graphics.Effects.IGraphicsEffect, Windows.Graphics.Effects.IGraphicsEffectSource
		{
			BlendEffect();

			BlendEffectMode Mode { get; set; };
			Windows.Graphics.Effects.IGraphicsEffectSource Background { get; set; };
			Windows.Graphics.Effects.IGraphicsEffectSource Foreground { get; set; };
		}
	}
}